In [2]:
import pandas as pd

In [3]:
tenders = pd.ExcelFile('data/Tender List.xlsx')

In [4]:
tenders.sheet_names

['Filtered Tenders', 'New Tenders']

In [ ]:
filtered_tenders = pd.read_excel(tenders, sheet_name='Filtered Tenders')

In [7]:
new_tenders = pd.read_excel(tenders, sheet_name='New Tenders')

In [9]:
filtered_tenders.shape

(84156, 26)

In [11]:
filtered_tenders.columns

Index(['Bidder',
       'Type of Bidder\n(Distributor/Integrator/Hospital/Manufacturer)',
       'Institution', 'Contract number', 'URL', 'Núm.', 'Clave CUCoP+',
       'Detailed description (ESP)', 'English', 'Irrelevant/Relevant',
       'Unit of measure - EN', 'Volume', 'Unit price without taxes (MXN)',
       'Unit price without taxes (MXN).1', 'IVA', 'Other taxes', 'Total',
       'Grupo', 'Minimum quantity', 'Maximum quantity',
       'Total amount minimum quantity (MXN)',
       'Total amount maximum amount (MXN)', 'Offer Amount (MXN)',
       'Total bid amount (MXN)', 'Start Date', 'End Date'],
      dtype='object')

In [14]:
filtered_tenders.head(3)

,Bidder,Type of Bidder\n(Distributor/Integrator/Hospital/Manufacturer),Institution,Contract number,URL,Núm.,Clave CUCoP+,Detailed description (ESP),English,Irrelevant/Relevant,...,Total,Grupo,Minimum quantity,Maximum quantity,Total amount minimum quantity (MXN),Total amount maximum amount (MXN),Offer Amount (MXN),Total bid amount (MXN),Start Date,End Date
0,TRANSPORTES ESPECIALIZADOS RUGA SA DE CV,NaN,050GYR - INSTITUTO MEXICANO DEL SEGURO SOCIAL,050GYR007N13625-001-00,https://comprasmx.buengobierno.gob.mx/sitiopub...,1.0,33901-0030,"SERVICIO DE RECOLECCION, TRANSPORTE EXTERNO Y ...","COLLECTION, EXTERNAL TRANSPORT AND FINAL DISPO...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"$336,000.00","$389,760.00",NaT,NaT
1,TRANSPORTES ESPECIALIZADOS RUGA SA DE CV,NaN,050GYR - INSTITUTO MEXICANO DEL SEGURO SOCIAL,050GYR007N13625-002-00,https://comprasmx.buengobierno.gob.mx/sitiopub...,1.0,33901-0030,"SERVICIO DE RECOLECCION, TRANSPORTE EXTERNO Y ...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"$252,000.00","$292,320.00",NaT,NaT
2,GRUPO ORTOMEMS SA DE CV,NaN,050GYR - INSTITUTO MEXICANO DEL SEGURO SOCIAL,050GYR007N13725-001-00,https://comprasmx.buengobierno.gob.mx/sitiopub...,1.0,25401-0371,1 MATERIAL DE OSTEOSINTESIS ZONA CUERNAVACA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"$24,709,712.07","$28,663,266.00",NaT,NaT

In [15]:
new_tenders.columns

Index(['Orden de gobierno', 'Clave Ramo', 'DescripciÛn Ramo',
       'Tipo de InstituciÛn', 'Clave InstituciÛn', 'Siglas de la InstituciÛn',
       'InstituciÛn', 'Clave de la UC', 'Nombre de la UC',
       'CÛdigo del expediente', 'Referencia del expediente',
       'TÌtulo del expediente', 'Translated', 'Irrelevant/Relevant',
       'Compra consolidada', 'Fecha de expediente', 'Tipo de elemento', 'Ley',
       'Tipo Procedimiento', 'ArtÌculo de excepciÛn', 'DescripciÛn excepciÛn',
       'Contrato marco', 'N˙m. Proc. Proyecto', 'Referencia anuncio',
       'Nombre anuncio', 'DescripciÛn anuncio', 'Operador anuncio',
       'Correo anuncio', 'Partida especÌfica', 'Tipo de contrataciÛn',
       'Caracter anuncio', 'Forma de participaciÛn', 'Entidad Federativa',
       'Fecha de publicaciÛn', 'Estatus procedimiento', 'Fecha apertura',
       'Fecha y hora junta de aclaraciones', 'Fecha de fallo',
       'DirecciÛn anuncio'],
      dtype='object')

In [4]:
latest.columns

Index(['Orden de gobierno', 'Clave Ramo', 'Descripción Ramo',
       'Tipo de Institución', 'Clave Institución', 'Siglas de la Institución',
       'Institución', 'Clave de la UC', 'Nombre de la UC',
       'Código del expediente', 'Referencia del expediente',
       'Título del expediente', 'Compra consolidada', 'Fecha de expediente',
       'Tipo de elemento', 'Ley', 'Tipo Procedimiento',
       'Artículo de excepción', 'Descripción excepción', 'Contrato marco',
       'Núm. Proc. Proyecto', 'Referencia anuncio', 'Nombre anuncio',
       'Descripción anuncio', 'Operador anuncio', 'Correo anuncio',
       'Partida específica', 'Tipo de contratación', 'Caracter anuncio',
       'Forma de participación', 'Entidad Federativa', 'Fecha de publicación',
       'Estatus procedimiento', 'Fecha apertura',
       'Fecha y hora junta de aclaraciones', 'Fecha de fallo',
       'Dirección anuncio'],
      dtype='object')

In [16]:
new_tenders.shape

(616, 39)

In [19]:
URL_COL = 'DirecciÛn anuncio'

print(*new_tenders[URL_COL].head())

https://comprasmx.buengobierno.gob.mx/sitiopublico/#/sitiopublico/detalle/0c434b009d084925aa384c1a3374ec1e/procedimiento https://comprasmx.buengobierno.gob.mx/sitiopublico/#/sitiopublico/detalle/e4cabbca2b054400aa75c373c8f6b31b/procedimiento https://comprasmx.buengobierno.gob.mx/sitiopublico/#/sitiopublico/detalle/1e4d442993fd457cb3ca305e6ec2715e/procedimiento https://comprasmx.buengobierno.gob.mx/sitiopublico/#/sitiopublico/detalle/611c20db83e841c09b63796b70e9391c/procedimiento https://comprasmx.buengobierno.gob.mx/sitiopublico/#/sitiopublico/detalle/20a29614e6584632a08f9136235a54cc/procedimiento

## Start Scraping

In [1]:
import pandas as pd

In [2]:
latest = pd.read_excel("data/New Tenders List_Q3 FY26.xlsx")
latest.shape

(1911, 37)

In [3]:
latest.columns

Index(['Orden de gobierno', 'Clave Ramo', 'Descripción Ramo',
       'Tipo de Institución', 'Clave Institución', 'Siglas de la Institución',
       'Institución', 'Clave de la UC', 'Nombre de la UC',
       'Código del expediente', 'Referencia del expediente',
       'Título del expediente', 'Compra consolidada', 'Fecha de expediente',
       'Tipo de elemento', 'Ley', 'Tipo Procedimiento',
       'Artículo de excepción', 'Descripción excepción', 'Contrato marco',
       'Núm. Proc. Proyecto', 'Referencia anuncio', 'Nombre anuncio',
       'Descripción anuncio', 'Operador anuncio', 'Correo anuncio',
       'Partida específica', 'Tipo de contratación', 'Caracter anuncio',
       'Forma de participación', 'Entidad Federativa', 'Fecha de publicación',
       'Estatus procedimiento', 'Fecha apertura',
       'Fecha y hora junta de aclaraciones', 'Fecha de fallo',
       'Dirección anuncio'],
      dtype='object')

Sanity Check

In [1]:
import pandas as pd

contracts = pd.read_csv("output_260126/step3_contracts_Sheet2.csv")
items = pd.read_csv("output_260126/step3_dialog_items_Sheet2.csv")


# Aggregate dialog items per contract
agg = (items
       .groupby(["URL", "contract_index", "Número de contrato"], as_index=False)
       .agg(
           items_count=("Subtotal (num)", "size"),
           subtotal_sum=("Subtotal (num)", "sum"),
           iva_sum=("IVA (num)", "sum"),
           otros_sum=("Otros impuestos (num)", "sum"),
           total_sum=("Total (num)", "sum"),
       ))

# Join against contract totals
chk = contracts.merge(
    agg,
    on=["URL", "contract_index", "Número de contrato"],
    how="left"
)

chk["diff_subtotal_vs_contract"] = chk["subtotal_sum"] - chk["Importe total sin impuestos (num)"]
chk["diff_total_vs_subtotal_plus_tax"] = chk["total_sum"] - (chk["subtotal_sum"] + chk["iva_sum"] + chk["otros_sum"])

print(chk[[
    "contract_index", "Número de contrato", "Licitante",
    "dialog_items_count", "items_count",
    "Importe total sin impuestos (num)", "subtotal_sum", "diff_subtotal_vs_contract",
    "iva_sum", "otros_sum", "total_sum", "diff_total_vs_subtotal_plus_tax"
]])

      contract_index      Número de contrato  \
0                  0                 S202602
1                  0                S 5M0132
2                  0     050GYR020N626-16-00
3                  0  050GYR001N00726-001-00
4                  0  050GYR030N02226-001-00
...              ...                     ...
2553               2        IB/BMX/0040/2026
2554               3        IB/BMX/0039/2026
2555               0                 D6P0001
2556               0  050GYR033N17725-208-00
2557               1  050GYR033N17725-209-00

                                    Licitante  dialog_items_count  \
0                              TAGAL SA DE CV                  16
1     LOGISTICA Y EQUIPOS BIOMEDICOS SA DE CV                  86
2                   ROBERTO ALMANZA VELAZQUEZ                   1
3                      IVANZA MEXICO SA DE CV                   1
4                 MELVIN YAIR MORALES MARQUEZ                   1
...                                       ...                 ...
2553                     CSL BEHRING SA DE CV                   1
2554                     CSL BEHRING SA DE CV                   1
2555           COMERCIALIZADORA LINI SA DE CV                   2
2556               JOSE TIBURCIO PEREZ GARCIA                   1
2557               PIOQUINTO MARTINEZ MENDOZA                   1

      items_count  Importe total sin impuestos (num)  subtotal_sum  \
0              16                        19319589.66           0.0
1              86                         6667958.00           0.0
2               1                                NaN           0.0
3               1                         2945992.19           0.0
4               1                                NaN           0.0
...           ...                                ...           ...
2553            1                                NaN           0.0
2554            1                                NaN           0.0
2555            2                                NaN           0.0
2556            1                                NaN           0.0
2557            1                                NaN           0.0

      diff_subtotal_vs_contract      iva_sum  otros_sum  total_sum  \
0                  -19319589.66  3091134.340        0.0        0.0
1                   -6667958.00   414403.232        0.0        0.0
2                           NaN        0.000        0.0        0.0
3                   -2945992.19   471358.750        0.0        0.0
4                           NaN        0.000        0.0        0.0
...                         ...          ...        ...        ...
2553                        NaN        0.000        0.0        0.0
2554                        NaN        0.000        0.0        0.0
2555                        NaN        0.000        0.0        0.0
2556                        NaN        0.000        0.0        0.0
2557                        NaN        0.000        0.0        0.0

      diff_total_vs_subtotal_plus_tax
0                        -3091134.340
1                         -414403.232
2                               0.000
3                         -471358.750
4                               0.000
...                               ...
2553                            0.000
2554                            0.000
2555                            0.000
2556                            0.000
2557                            0.000

[2558 rows x 12 columns]

In [5]:
import json
from glob import glob as g

In [6]:
raw_urls = g('output_260126/by_url/Sheet2/*.json', recursive=True)

In [7]:
len(raw_urls)

1911

In [8]:
raw_urls[0]

'output_260126/by_url/Sheet2\\002624839396af52563fa3d6204d4c24de98fa7f.json'

In [9]:
raw_data = json.load(open(raw_urls[0], 'r', encoding='utf-8'))

In [14]:
raw_data.keys()

dict_keys(['url', 'ok', 'attempts', 'error_kind', 'error', 'page_kv', 'all_tables', 'contracts'])

In [17]:
raw_data['url']

'https://comprasmx.buengobierno.gob.mx/sitiopublico/#/sitiopublico/detalle/68b48c6784ee44ed95b99b87eaf26924/procedimiento'

In [15]:
raw_data['contracts'][0].keys()

dict_keys(['contract_index', 'contract_number_clicked', 'contract_row', 'dialog_tables', 'dialog_items_count', 'dialog_items'])

In [16]:
raw_data['contracts']

[{'contract_index': 0,
  'contract_number_clicked': 'S202602',
  'contract_row': {'Núm.': '1',
   'Licitante': 'TAGAL SA DE CV',
   'Número de contrato': 'S202602',
   'Titulo contrato': 'SUMINISTRO DE DIÉSEL BAJO EN AZUFRE',
   'Estatus contrato': 'PUBLICADO',
   'Fecha inicio': '01/01/2026',
   'Fecha fin': '31/12/2026',
   'Importe total sin impuestos': '$19,319,589.66',
   'Moneda': 'MXN'},
  'dialog_tables': [{'dialog_table_index': 0,
    'table': {'headers': ['Clave CUCoP+',
      'Descripción detallada',
      'Unidad de medida',
      'Precio unitario sin impuestos',
      'Monto de la Oferta',
      'IVA',
      'Otros impuestos',
      'Monto total de la oferta'],
     'rows': [{'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA CÓRDOBA - H.G.Z. NO. 8 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$22.41',
       'Monto de la Oferta': '$2,223,352.59',
       'IVA': '$355,736.42',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$2,579,089.01'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 12 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$22.41',
       'Monto de la Oferta': '$0.00',
       'IVA': '$0.00',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$0.00'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 16 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$22.41',
       'Monto de la Oferta': '$0.00',
       'IVA': '$0.00',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$0.00'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 19 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$22.41',
       'Monto de la Oferta': '$0.00',
       'IVA': '$0.00',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$0.00'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 33 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$22.41',
       'Monto de la Oferta': '$0.00',
       'IVA': '$0.00',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$0.00'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA CÓRDOBA - U.M.F. NO. 64 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$22.41',
       'Monto de la Oferta': '$0.00',
       'IVA': '$0.00',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$0.00'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA ORIZABA - H.G.R.O. PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$22.51',
       'Monto de la Oferta': '$3,965,517.24',
       'IVA': '$634,482.76',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$4,600,000.00'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA COSAMALOAPAN - H.G.Z. NO. 35 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$22.16',
       'Monto de la Oferta': '$4,906,090.52',
       'IVA': '$784,974.48',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$5,691,065.00'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA COSAMALOAPAN - U.M.F. NO. 43 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$22.16',
       'Monto de la Oferta': '$0.00',
       'IVA': '$0.00',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$0.00'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA MINATITILÁN - H.G.Z. 32 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$21.87',
       'Monto de la Oferta': '$2,801,297.41',
       'IVA': '$448,207.58',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$3,249,504.99'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 52 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$21.87',
       'Monto de la Oferta': '$0.00',
       'IVA': '$0.00',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$0.00'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 51 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$21.87',
       'Monto de la Oferta': '$0.00',
       'IVA': '$0.00',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$0.00'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 34 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$21.87',
       'Monto de la Oferta': '$0.00',
       'IVA': '$0.00',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$0.00'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 57 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$21.87',
       'Monto de la Oferta': '$0.00',
       'IVA': '$0.00',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$0.00'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA COATZACOALCOS - H.G.Z NO 36 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$21.85',
       'Monto de la Oferta': '$5,423,331.90',
       'IVA': '$867,733.10',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$6,291,065.00'},
      {'Clave CUCoP+': '26105-0030',
       'Descripción detallada': 'ZONA COATZACOALCOS - U.M.F. NO. 69 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
       'Unidad de medida': 'UNIDAD',
       'Precio unitario sin impuestos': '$21.85',
       'Monto de la Oferta': '$0.00',
       'IVA': '$0.00',
       'Otros impuestos': '$0.00',
       'Monto total de la oferta': '$0.00'}],
     'row_count': 16},
    'had_pagination': True,
    'pages_visited': 1,
    'paginator_text': '',
    'expected_total_rows': None,
    'pagination_warning': None}],
  'dialog_items_count': 16,
  'dialog_items': [{'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA CÓRDOBA - H.G.Z. NO. 8 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$22.41',
     'Monto de la Oferta': '$2,223,352.59',
     'IVA': '$355,736.42',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$2,579,089.01'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 12 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$22.41',
     'Monto de la Oferta': '$0.00',
     'IVA': '$0.00',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$0.00'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 16 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$22.41',
     'Monto de la Oferta': '$0.00',
     'IVA': '$0.00',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$0.00'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 19 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$22.41',
     'Monto de la Oferta': '$0.00',
     'IVA': '$0.00',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$0.00'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 33 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$22.41',
     'Monto de la Oferta': '$0.00',
     'IVA': '$0.00',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$0.00'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA CÓRDOBA - U.M.F. NO. 64 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$22.41',
     'Monto de la Oferta': '$0.00',
     'IVA': '$0.00',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$0.00'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA ORIZABA - H.G.R.O. PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$22.51',
     'Monto de la Oferta': '$3,965,517.24',
     'IVA': '$634,482.76',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$4,600,000.00'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA COSAMALOAPAN - H.G.Z. NO. 35 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$22.16',
     'Monto de la Oferta': '$4,906,090.52',
     'IVA': '$784,974.48',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$5,691,065.00'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA COSAMALOAPAN - U.M.F. NO. 43 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$22.16',
     'Monto de la Oferta': '$0.00',
     'IVA': '$0.00',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$0.00'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA MINATITILÁN - H.G.Z. 32 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$21.87',
     'Monto de la Oferta': '$2,801,297.41',
     'IVA': '$448,207.58',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$3,249,504.99'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 52 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$21.87',
     'Monto de la Oferta': '$0.00',
     'IVA': '$0.00',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$0.00'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 51 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$21.87',
     'Monto de la Oferta': '$0.00',
     'IVA': '$0.00',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$0.00'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 34 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$21.87',
     'Monto de la Oferta': '$0.00',
     'IVA': '$0.00',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$0.00'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 57 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$21.87',
     'Monto de la Oferta': '$0.00',
     'IVA': '$0.00',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$0.00'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA COATZACOALCOS - H.G.Z NO 36 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$21.85',
     'Monto de la Oferta': '$5,423,331.90',
     'IVA': '$867,733.10',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$6,291,065.00'}},
   {'dialog_table_index': 0,
    'row': {'Clave CUCoP+': '26105-0030',
     'Descripción detallada': 'ZONA COATZACOALCOS - U.M.F. NO. 69 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
     'Unidad de medida': 'UNIDAD',
     'Precio unitario sin impuestos': '$21.85',
     'Monto de la Oferta': '$0.00',
     'IVA': '$0.00',
     'Otros impuestos': '$0.00',
     'Monto total de la oferta': '$0.00'}}]}]

In [21]:
pre_keys = raw_data.keys()
for pre in pre_keys:
    print(pre, type(raw_data[pre]))
    print(raw_data[pre])

url <class 'str'>
https://comprasmx.buengobierno.gob.mx/sitiopublico/#/sitiopublico/detalle/68b48c6784ee44ed95b99b87eaf26924/procedimiento
ok <class 'bool'>
True
attempts <class 'int'>
1
error_kind <class 'NoneType'>
None
error <class 'NoneType'>
None
page_kv <class 'dict'>
{'page_titles': ['LICITACIÓN PÚBLICA', 'DATOS GENERALES', 'REQUERIMIENTOS', '1. DIESEL BAJO EN AZUFRE - ZONA ORIZABA', '2. DIESEL BAJO EN AZUFRE - ZONA CÓRDOBA', '3. DIESEL BAJO EN AZUFRE - ZONA COSAMALOAPAN', '4. DIESEL BAJO EN AZUFRE - ZONA MINATITLÁN', '5. DIESEL BAJO EN AZUFRE - ZONA COATZACOALCOS'], 'Código del expediente': 'E-2025-00110602', 'Número de procedimiento de contratación': ['LA-50-GYR-050GYR022-N-2-2026', 'LA-50-GYR-050GYR022-N-2-2026'], 'Estatus del procedimiento de contratación': 'ADJUDICADO', 'Compra consolidada': 'NO', 'Dependencia o Entidad': '050GYR - INSTITUTO MEXICANO DEL SEGURO SOCIAL', 'Ramo': '50 - INSTITUTO MEXICANO DEL SEGURO SOCIAL', 'Unidad compradora': '050GYR022 COORDINACION DE ABASTECIMIENTO Y EQUIPAMIENTO VERACRUZ SUR', 'Responsable de la captura': 'JOSE EDUARDO TORRES LEAL', 'Correo electrónico unidad compradora': 'jose.torresle@imss.gob.mx', 'Referencia / Número de control interno': 'LA-50-GYR-050GYR022-N-2-2026', 'Nombre del procedimiento de contratación': 'SUMINISTRO DE DIÉSEL BAJO EN AZUFRE', 'Descripción detallada del procedimiento de contratación': 'LA-50-GYR-050GYR022-N-2-2026 LICITACIÓN PÚBLICA NACIONAL ELECTRÓNICA PARA LA CONTRATACIÓN DEL SERVICIO DE SUMINISTRO DE DIÉSEL BAJO EN AZUFRE, CUBRIENDO NECESIDADES EN EL ÁMBITO DEL ÓRGANO DE OPERACIÓN ADMINISTRATIVA DESCONCENTRADA REGIONAL VERACRUZ SUR DEL INSTITUTO MEXICANO DEL SEGURO SOCIAL. EJERCICIO 2026.', 'Ley/Soporte normativo que rige la contratación': 'LEY DE ADQUISICIONES, ARRENDAMIENTOS Y SERVICIOS DEL SECTOR PÚBLICO', 'Tipo de procedimiento de contratación': 'LICITACIÓN PÚBLICA', 'Entidad Federativa donde se llevará a cabo la contratación': 'VERACRUZ', 'Año del ejercicio presupuestal': '2026', 'Código del proyecto de convocatoria': 'PC-2025-00001997', 'Procedimiento exclusivo para MIPYMES': 'NO', 'Fecha y hora de publicación': '04/12/2025 10:02', 'Fecha y hora de presentación y apertura de proposiciones': '18/12/2025 09:30', 'Lugar de apertura de proposiciones': 'SALA DE JUNTAS DE LA COORDINACIÓN DE ABASTECIMIENTO Y EQUIPAMIENTO, CITO EN AVENIDA VERACRUZ ESQUINA CALLE NORTE 22 NO. 56, COL. SANTA CATARINA, RÍO BLANCO, VERACRUZ.', 'Fecha y hora de junta de aclaraciones': '09/12/2025 09:30', 'Fecha y hora límite para envío de aclaraciones a través de Compras MX': '08/12/2025 09:30', 'Lugar de la junta de aclaraciones': 'SALA DE JUNTAS DE LA COORDINACIÓN DE ABASTECIMIENTO Y EQUIPAMIENTO, CITO EN AVENIDA VERACRUZ ESQUINA CALLE NORTE 22 NO. 56, COL. SANTA CATARINA, RÍO BLANCO, VERACRUZ.', 'Plazo del procedimiento de contratación': 'RECORTADO', 'Justificación del plazo recortado': 'SE REALICE A PLAZOS RECORTADOS, YA QUE ES UN SERVICIO PRIORITARIO PARA LA OPERACIÓN DE LOS HOSPITALES Y UNIDADES MÉDICAS QUE IMPACTA DIRECTAMENTE EN LA ATENCIÓN MÉDICA', 'Fecha y hora del acto del Fallo': '26/12/2025 09:30', 'Lugar del acto del Fallo': 'SALA DE JUNTAS DE LA COORDINACIÓN DE ABASTECIMIENTO Y EQUIPAMIENTO, CITO EN AVENIDA VERACRUZ ESQUINA CALLE NORTE 22 NO. 56, COL. SANTA CATARINA, RÍO BLANCO, VERACRUZ.', 'Fecha estimada del inicio del contrato': '22/01/2026', 'Participación de Testigo Social': 'NO', 'Tipo de contratación': 'SERVICIOS', 'Criterio de evaluación': 'BINARIO', 'Medio o forma de participación': 'ELECTRÓNICA', 'Carácter': 'NACIONAL', 'Idioma(s) de presentación de proposiciones': 'ESPAÑOL', 'Abastecimiento simultáneo': 'NO', 'Anticipo': 'NO', 'Caso fortuito o fuerza mayor': 'NO', 'Se usará la modalidad de Ofertas Subsecuentes de Descuentos': 'NO', 'Moneda': 'PESO MEXICANO', '¿Permite participación conjunta?': 'SI', 'Contrato Abierto': 'SI', 'Tipo de Contrato Abierto': 'MONTO', 'Es plurianual': 'NO', 'Forma de pago': 'GENERALMENTE REALIZADA VÍA TRANSFERENCIA BANCARIA, PREVIO VISTO BUENO DE LA DOCUMENTACIÓN SOLICITADA POR EL ÁREA DE FINANZAS PARA GESTIÓN DE SU PAGO INSTITUTO MEXICANO DEL SEGURO SOCIAL', 'Garantía de cumplimiento': 'SI', 'Porcentaje del monto del contrato a garantizar': '10', 'Plazo en días para entregar la garantía': '10', 'A nombre de': 'INSTITUTO MEXICANO DEL SEGURO SOCIAL', 'Garantía sobre el bien o servicio y vicios ocultos': 'NO', 'Otros seguros': 'NO', 'Crédito externo': 'NO'}
all_tables <class 'list'>
[{'index': 0, 'context': '', 'table': {'headers': [], 'rows': [{'value': '050GYR022 - COORDINACION DE ABASTECIMIENTO Y EQUIPAMIENTO VERACRUZ SUR'}], 'row_count': 1}}, {'index': 1, 'context': '', 'table': {'headers': ['Clave', 'Descripción'], 'rows': [{'Clave': '26105', 'Descripción': 'COMBUSTIBLES, LUBRICANTES Y ADITIVOS PARA MAQUINARIA, EQUIPO DE PRODUCCIÓN Y SERVICIOS ADMINISTRATIVOS'}], 'row_count': 1}}, {'index': 2, 'context': '', 'table': {'headers': ['Núm.', 'Tipo de documento', 'Descripción', 'Total de Archivos', 'Acciones'], 'rows': [{'Núm.': '1', 'Tipo de documento': 'CONVOCATORIA', 'Descripción': 'CONVOCATORIA', 'Total de Archivos': '', 'Acciones': ''}, {'Núm.': '2', 'Tipo de documento': 'ANEXO TÉCNICO', 'Descripción': 'ANEXO TÉCNICO', 'Total de Archivos': '', 'Acciones': ''}, {'Núm.': '3', 'Tipo de documento': 'MODELO DE CONTRATO', 'Descripción': 'MODELO DE CONTRATO', 'Total de Archivos': '', 'Acciones': ''}, {'Núm.': '4', 'Tipo de documento': 'AVISO DE SUSPENSIÓN DE JUNTA DE ACLARACIONES', 'Descripción': 'AVISO DE SUSPENSIÓN DE JUNTA DE ACLARACIONES', 'Total de Archivos': '', 'Acciones': ''}, {'Núm.': '5', 'Tipo de documento': 'ACTA JUNTA DE ACLARACIONES', 'Descripción': 'ACTA JUNTA DE ACLARACIONES', 'Total de Archivos': '', 'Acciones': ''}, {'Núm.': '6', 'Tipo de documento': 'ANEXOS ACTA DE JUNTA DE ACLARACIONES', 'Descripción': 'ANEXOS ACTA DE JUNTA DE ACLARACIONES', 'Total de Archivos': '', 'Acciones': ''}, {'Núm.': '7', 'Tipo de documento': 'ACTA CIERRE JUNTA DE ACLARACIONES', 'Descripción': 'ACTA CIERRE JUNTA DE ACLARACIONES', 'Total de Archivos': '', 'Acciones': ''}, {'Núm.': '8', 'Tipo de documento': 'ACTA DE APERTURA DE PROPOSICIONES', 'Descripción': 'ACTA DE APERTURA DE PROPOSICIONES', 'Total de Archivos': '', 'Acciones': ''}, {'Núm.': '9', 'Tipo de documento': 'ACTA DE FALLO', 'Descripción': 'ACTA DE FALLO', 'Total de Archivos': '', 'Acciones': ''}], 'row_count': 9}}, {'index': 3, 'context': '', 'table': {'headers': ['Núm.', 'Licitante', 'Número de contrato', 'Titulo contrato', 'Estatus contrato', 'Fecha inicio', 'Fecha fin', 'Importe total sin impuestos', 'Moneda'], 'rows': [{'Núm.': '1', 'Licitante': 'TAGAL SA DE CV', 'Número de contrato': 'S202602', 'Titulo contrato': 'SUMINISTRO DE DIÉSEL BAJO EN AZUFRE', 'Estatus contrato': 'PUBLICADO', 'Fecha inicio': '01/01/2026', 'Fecha fin': '31/12/2026', 'Importe total sin impuestos': '$19,319,589.66', 'Moneda': 'MXN'}], 'row_count': 1}}, {'index': 4, 'context': '', 'table': {'headers': ['Núm.', 'Partida específica', 'Clave CUCoP+', 'Descripción CUCoP+', 'Descripción detallada', 'Unidad de medida'], 'rows': [{'Núm.': '1', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA ORIZABA - H.G.R.O. PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}], 'row_count': 1}}, {'index': 5, 'context': '', 'table': {'headers': ['Núm.', 'Partida específica', 'Clave CUCoP+', 'Descripción CUCoP+', 'Descripción detallada', 'Unidad de medida'], 'rows': [{'Núm.': '1', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA CÓRDOBA - H.G.Z. NO. 8 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}, {'Núm.': '2', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 12 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}, {'Núm.': '3', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 16 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}, {'Núm.': '4', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 19 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}, {'Núm.': '5', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 33 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}, {'Núm.': '6', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA CÓRDOBA - U.M.F. NO. 64 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}], 'row_count': 6}}, {'index': 6, 'context': '', 'table': {'headers': ['Núm.', 'Partida específica', 'Clave CUCoP+', 'Descripción CUCoP+', 'Descripción detallada', 'Unidad de medida'], 'rows': [{'Núm.': '1', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA COSAMALOAPAN - H.G.Z. NO. 35 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}, {'Núm.': '2', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA COSAMALOAPAN - U.M.F. NO. 43 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}], 'row_count': 2}}, {'index': 7, 'context': '', 'table': {'headers': ['Núm.', 'Partida específica', 'Clave CUCoP+', 'Descripción CUCoP+', 'Descripción detallada', 'Unidad de medida'], 'rows': [{'Núm.': '1', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA MINATITILÁN - H.G.Z. 32 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}, {'Núm.': '2', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 52 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}, {'Núm.': '3', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 51 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}, {'Núm.': '4', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 34 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}, {'Núm.': '5', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 57 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}], 'row_count': 5}}, {'index': 8, 'context': '', 'table': {'headers': ['Núm.', 'Partida específica', 'Clave CUCoP+', 'Descripción CUCoP+', 'Descripción detallada', 'Unidad de medida'], 'rows': [{'Núm.': '1', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA COATZACOALCOS - H.G.Z NO 36 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}, {'Núm.': '2', 'Partida específica': '26105', 'Clave CUCoP+': '26105-0030', 'Descripción CUCoP+': 'DIESEL', 'Descripción detallada': 'ZONA COATZACOALCOS - U.M.F. NO. 69 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO', 'Unidad de medida': 'UNIDAD'}], 'row_count': 2}}]
contracts <class 'list'>

In [24]:
raw_data['page_kv'].keys()

dict_keys(['page_titles', 'Código del expediente', 'Número de procedimiento de contratación', 'Estatus del procedimiento de contratación', 'Compra consolidada', 'Dependencia o Entidad', 'Ramo', 'Unidad compradora', 'Responsable de la captura', 'Correo electrónico unidad compradora', 'Referencia / Número de control interno', 'Nombre del procedimiento de contratación', 'Descripción detallada del procedimiento de contratación', 'Ley/Soporte normativo que rige la contratación', 'Tipo de procedimiento de contratación', 'Entidad Federativa donde se llevará a cabo la contratación', 'Año del ejercicio presupuestal', 'Código del proyecto de convocatoria', 'Procedimiento exclusivo para MIPYMES', 'Fecha y hora de publicación', 'Fecha y hora de presentación y apertura de proposiciones', 'Lugar de apertura de proposiciones', 'Fecha y hora de junta de aclaraciones', 'Fecha y hora límite para envío de aclaraciones a través de Compras MX', 'Lugar de la junta de aclaraciones', 'Plazo del procedimiento de contratación', 'Justificación del plazo recortado', 'Fecha y hora del acto del Fallo', 'Lugar del acto del Fallo', 'Fecha estimada del inicio del contrato', 'Participación de Testigo Social', 'Tipo de contratación', 'Criterio de evaluación', 'Medio o forma de participación', 'Carácter', 'Idioma(s) de presentación de proposiciones', 'Abastecimiento simultáneo', 'Anticipo', 'Caso fortuito o fuerza mayor', 'Se usará la modalidad de Ofertas Subsecuentes de Descuentos', 'Moneda', '¿Permite participación conjunta?', 'Contrato Abierto', 'Tipo de Contrato Abierto', 'Es plurianual', 'Forma de pago', 'Garantía de cumplimiento', 'Porcentaje del monto del contrato a garantizar', 'Plazo en días para entregar la garantía', 'A nombre de', 'Garantía sobre el bien o servicio y vicios ocultos', 'Otros seguros', 'Crédito externo'])

In [25]:
pd.DataFrame([raw_data['page_kv']])

,page_titles,Código del expediente,Número de procedimiento de contratación,Estatus del procedimiento de contratación,Compra consolidada,Dependencia o Entidad,Ramo,Unidad compradora,Responsable de la captura,Correo electrónico unidad compradora,...,Tipo de Contrato Abierto,Es plurianual,Forma de pago,Garantía de cumplimiento,Porcentaje del monto del contrato a garantizar,Plazo en días para entregar la garantía,A nombre de,Garantía sobre el bien o servicio y vicios ocultos,Otros seguros,Crédito externo
0,"[LICITACIÓN PÚBLICA, DATOS GENERALES, REQUERIM...",E-2025-00110602,"[LA-50-GYR-050GYR022-N-2-2026, LA-50-GYR-050GY...",ADJUDICADO,NO,050GYR - INSTITUTO MEXICANO DEL SEGURO SOCIAL,50 - INSTITUTO MEXICANO DEL SEGURO SOCIAL,050GYR022 COORDINACION DE ABASTECIMIENTO Y EQU...,JOSE EDUARDO TORRES LEAL,jose.torresle@imss.gob.mx,...,MONTO,NO,GENERALMENTE REALIZADA VÍA TRANSFERENCIA BANCA...,SI,10,10,INSTITUTO MEXICANO DEL SEGURO SOCIAL,NO,NO,NO

In [28]:
len(raw_data['contracts'])

1

In [31]:
type(raw_data['contracts'][0])

dict

In [33]:
raw_data['contracts'][0].keys()

dict_keys(['contract_index', 'contract_number_clicked', 'contract_row', 'dialog_tables', 'dialog_items_count', 'dialog_items'])

In [34]:
for k in raw_data['contracts'][0].keys():
    print(k, type(raw_data['contracts'][0][k]))

contract_index <class 'int'>
contract_number_clicked <class 'str'>
contract_row <class 'dict'>
dialog_tables <class 'list'>
dialog_items_count <class 'int'>
dialog_items <class 'list'>

In [35]:
raw_data['contracts'][0]['contract_row']

{'Núm.': '1',
 'Licitante': 'TAGAL SA DE CV',
 'Número de contrato': 'S202602',
 'Titulo contrato': 'SUMINISTRO DE DIÉSEL BAJO EN AZUFRE',
 'Estatus contrato': 'PUBLICADO',
 'Fecha inicio': '01/01/2026',
 'Fecha fin': '31/12/2026',
 'Importe total sin impuestos': '$19,319,589.66',
 'Moneda': 'MXN'}

In [47]:
pd.DataFrame(raw_data['contracts'][0]['dialog_tables'])

,dialog_table_index,table,had_pagination,pages_visited,paginator_text,expected_total_rows,pagination_warning
0,0,"{'headers': ['Clave CUCoP+', 'Descripción deta...",True,1,,None,None

In [ ]:
raw_data['contracts'][0]['dialog_items_count']

16

In [39]:
raw_data['contracts'][0]['dialog_items']

[{'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA CÓRDOBA - H.G.Z. NO. 8 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$22.41',
   'Monto de la Oferta': '$2,223,352.59',
   'IVA': '$355,736.42',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$2,579,089.01'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 12 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$22.41',
   'Monto de la Oferta': '$0.00',
   'IVA': '$0.00',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$0.00'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 16 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$22.41',
   'Monto de la Oferta': '$0.00',
   'IVA': '$0.00',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$0.00'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 19 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$22.41',
   'Monto de la Oferta': '$0.00',
   'IVA': '$0.00',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$0.00'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA CÓRDOBA - H.G.S.Z. NO. 33 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$22.41',
   'Monto de la Oferta': '$0.00',
   'IVA': '$0.00',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$0.00'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA CÓRDOBA - U.M.F. NO. 64 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$22.41',
   'Monto de la Oferta': '$0.00',
   'IVA': '$0.00',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$0.00'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA ORIZABA - H.G.R.O. PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$22.51',
   'Monto de la Oferta': '$3,965,517.24',
   'IVA': '$634,482.76',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$4,600,000.00'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA COSAMALOAPAN - H.G.Z. NO. 35 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$22.16',
   'Monto de la Oferta': '$4,906,090.52',
   'IVA': '$784,974.48',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$5,691,065.00'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA COSAMALOAPAN - U.M.F. NO. 43 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$22.16',
   'Monto de la Oferta': '$0.00',
   'IVA': '$0.00',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$0.00'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA MINATITILÁN - H.G.Z. 32 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$21.87',
   'Monto de la Oferta': '$2,801,297.41',
   'IVA': '$448,207.58',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$3,249,504.99'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 52 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$21.87',
   'Monto de la Oferta': '$0.00',
   'IVA': '$0.00',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$0.00'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 51 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$21.87',
   'Monto de la Oferta': '$0.00',
   'IVA': '$0.00',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$0.00'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 34 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$21.87',
   'Monto de la Oferta': '$0.00',
   'IVA': '$0.00',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$0.00'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA MINATITILÁN - UMF NO. 57 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$21.87',
   'Monto de la Oferta': '$0.00',
   'IVA': '$0.00',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$0.00'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA COATZACOALCOS - H.G.Z NO 36 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$21.85',
   'Monto de la Oferta': '$5,423,331.90',
   'IVA': '$867,733.10',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$6,291,065.00'}},
 {'dialog_table_index': 0,
  'row': {'Clave CUCoP+': '26105-0030',
   'Descripción detallada': 'ZONA COATZACOALCOS - U.M.F. NO. 69 PRECIO UNITARIO POR LITRO DE DIESEL INDUSTRIAL BAJO EN AZUFRE PARA MAQUINARIA SIN INCLUIR IMPUESTO',
   'Unidad de medida': 'UNIDAD',
   'Precio unitario sin impuestos': '$21.85',
   'Monto de la Oferta': '$0.00',
   'IVA': '$0.00',
   'Otros impuestos': '$0.00',
   'Monto total de la oferta': '$0.00'}}]